# Generated by Django 2.0.5 on 2018-07-27 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Custom_Circuit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workouts', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Custom_Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredients', models.TextField()),
                ('instructions', models.TextField()),
                ('portions', models.TextField()),
                ('macros', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('passworld', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=10)),
                ('weight', models.CharField(max_length=10)),
                ('height', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='custom_meal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='fitness_app.User'),
        ),
        migrations.AddField(
            model_name='custom_circuit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circuits', to='fitness_app.User'),
        ),
    ]
