# Generated by Django 2.0.5 on 2018-08-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='muscles',
            field=models.TextField(blank=True, null=True),
        ),
    ]
