# Generated by Django 2.0.5 on 2018-08-01 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0005_custom_circuit_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_meal',
            name='label',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
