# Generated by Django 2.0.5 on 2018-08-02 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0008_workout_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='workoutid',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
