# Generated by Django 2.0.5 on 2018-08-02 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0009_workout_workoutid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='muscles',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='user',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to=settings.AUTH_USER_MODEL),
        ),
    ]
