# Generated by Django 2.0.5 on 2018-08-02 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0010_auto_20180802_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='workoutid',
        ),
        migrations.AlterField(
            model_name='workout',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='workout',
            name='user',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to=settings.AUTH_USER_MODEL),
        ),
    ]
