# Generated by Django 2.0.5 on 2018-08-02 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0011_auto_20180802_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='id',
            field=models.CharField(max_length=1000, primary_key=True, serialize=False),
        ),
    ]
