# Generated by Django 2.0.5 on 2018-08-02 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0012_auto_20180802_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='workoutId',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='workout',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
